# Generated by Django 5.0.4 on 2024-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_rename_title_image_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
