# Generated by Django 5.0.4 on 2024-04-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CATEGORIA1', 'Categoria1'), ('CATEGORIA2', 'Categoria2'), ('CATEGORIA3', 'Categoria3'), ('CATEGORIA4', 'Categoria4')], default='', max_length=100),
        ),
    ]
