# Generated by Django 5.0.4 on 2024-04-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='images/logos%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(max_length=6)),
                ('secondary_color', models.CharField(max_length=6)),
                ('tertiary_color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.logo')),
                ('styles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.styles')),
            ],
        ),
    ]
