# Generated by Django 5.0.4 on 2024-04-15 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('credits', models.CharField(max_length=100)),
                ('picture_date', models.DateTimeField(default=datetime.datetime.now)),
                ('picture', models.ImageField(blank=True, upload_to='pictures/%Y/%m/%d')),
            ],
        ),
    ]
