# Generated by Django 5.0.4 on 2024-04-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='image_title',
        ),
    ]
